apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ cookiecutter.k8s_namespace }}

resources:
- ../../base

patches:
- path: ./deployment-patch.yaml
  target:
    kind: Deployment
- path: ./ingress-patch.yaml
  target:
    kind: Ingress

images:
- name: {{ cookiecutter.acr_name }}.azurecr.io/{{ cookiecutter.image_name }}
  newName: {{ cookiecutter.acr_name }}.azurecr.io/{{ cookiecutter.image_name }}
  newTag: v2.1.2
