apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.image_name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ cookiecutter.argocd_ip }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ cookiecutter.image_name }}-svc
            port:
              number: 80
        pathType: Prefix