spring:
  profiles:
    active: local
  application:
    name: {{ cookiecutter.project_name }}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_username
    password: your_password
  sql:
    init:
      mode: always
      schema-locations: classpath:conf/db/schema.sql
      data-locations: classpath:conf/db/data.sql


server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.kt.{{ cookiecutter.package_name }}: DEBUG
    org.springframework: INFO
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import: application-dev.yml

---
spring:
  config:
    activate:
      on-profile: stg
    import: application-stg.yml

---
spring:
  config:
    activate:
      on-profile: prd
    import: application-prd.yml
