spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sampledb
    username: dbuser
    password: password

logging:
  level:
    {{ cookiecutter.package_name }}: DEBUG
    org.springframework: DEBUG
    org.mybatis: DEBUG 