spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: localuser
    password: localpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    {{ cookiecutter.package_name }}: DEBUG
      org.springframework: DEBUG
      org.mybatis: DEBUG 
