apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.project_name }}
  description: {{ cookiecutter.description }}
  annotations:
    github.com/project-slug: poplar0713/{{ cookiecutter.github_repo_name }}
    backstage.io/kubernetes-id: {{ cookiecutter.project_name }}
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: {{ cookiecutter.argocd_app_name }}
    jira/project-key: 'KAN'
    azure-container-registry/repository-name: {{ cookiecutter.image_name }}
    backstage.io/techdocs-ref: dir:.
    
spec:
  type: service
  lifecycle: experimental
  owner: {{ cookiecutter.owner }}