name: Build and upload JAR to Blob

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - ubuntu-latest
      environment:
        description: "Deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  build:
    name: (${{ inputs.environment }}) Build using Gradle
    runs-on: "${{ inputs.runner }}"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Find built JAR
        id: find_jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "::set-output name=jar_path::$JAR_PATH"

      - name: Log in to Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credentials.json
          az login --service-principal \
            --username $(jq -r .clientId azure_credentials.json) \
            --password $(jq -r .clientSecret azure_credentials.json) \
            --tenant $(jq -r .tenantId azure_credentials.json)
          az account set --subscription $(jq -r .subscriptionId azure_credentials.json)

      - name: Upload jar file to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name "${{ vars.AZURE_STORAGE_ACCOUNT }}" \
            --container-name "${{ vars.AZURE_ARTIFACT_CONTAINER }}" \
            --file "$JAR_PATH" \
            --name "${{ vars.APP_NAME }}-${{ inputs.environment }}.jar" \
            --overwrite \
            --auth-mode login