name: Deploy to ArgoCD with ACR docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.26.0'

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_IP }} --username ${{ secrets.ARGOCD_ID }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Create ArgoCD secret for ACR
        run: |
          kubectl create secret docker-registry acr-credentials \
          --docker-server ${{ vars.ACR_NAME }}.azurecr.io \
          --docker-username ${{ vars.DOCKER_USERNAME }} \
          --docker-password ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if ArgoCD app exists
        id: check_app
        run: |
          if argocd app get ${{ vars.ARGOCD_APP_NAME }}; then
            echo "app_exists=true" >> $GITHUB_ENV
          else
            echo "app_exists=false" >> $GITHUB_ENV
          fi

      - name: Create or Update ArgoCD Application
        run: |
          if [ "${{ env.app_exists }}" = "true" ]; then
            argocd app set ${{ vars.ARGOCD_APP_NAME }} \
              --repo https://github.com/${{ github.repository }} \
              --path manifests/overlays/${{ github.event.inputs.environment }} \
              --sync-policy automated
              --dest-namespace ${{ vars.K8S_NAMESPACE }}
          else
            argocd app create ${{ vars.ARGOCD_APP_NAME }} \
              --repo https://github.com/${{ github.repository }} \
              --path manifests/overlays/${{ github.event.inputs.environment }} \
              --dest-server https://kubernetes.default.svc \
              --dest-namespace ${{ vars.K8S_NAMESPACE }}  \
              --sync-policy automated
          fi

      - name: ArgoCD Sync Application
        run: |
          argocd app sync ${{ vars.ARGOCD_APP_NAME }}
