apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.image_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.image_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.image_name }}
        backstage.io/kubernetes-id: {{ cookiecutter.project_name }}
    spec:
      containers:
        - name: {{ cookiecutter.image_name }}
          image: {{ cookiecutter.acr_name }}.azurecr.io/{{ cookiecutter.image_name }}-dev
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"