apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.image_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.image_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.image_name }}
        backstage.io/kubernetes-id: {{ cookiecutter.project_name }}
    spec:
      containers:
        - name: {{ cookiecutter.image_name }}
          image: {{ cookiecutter.acr_name }}.azurecr.io/{{ cookiecutter.repository_name }}/{{ cookiecutter.image_name }}:v1.0.0
          ports:
          - containerPort: 8080