apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.project_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_name }}
    spec:
      containers:
        - name: {{ cookiecutter.project_name }}
          image: ktdseduacr.azurecr.io/edu08/samplejava:v1.0.0
          ports:
          - containerPort: 8080