apiVersion: v1
kind: Service
metadata:
    name:  {{ cookiecutter.project_name }}-svc
spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: {{ cookiecutter.project_name }}
