apiVersion: v1
kind: Service
metadata:
    name:  {{ cookiecutter.image_name }}-svc
spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: {{ cookiecutter.image_name }}
